<!-- in pandas we use for  -->
<!-- in xl we con't work for the  -->
<!-- mixed types we can do  -->

In [41]:
import pandas as pb
# numpy vs pandas
# in numpy we can't use the different data to integer, float, string
# but in pandas we can use the different data to integer, float, string
# numpy us for image processing, machine learning, deep learning
# pandas is for data analysis, data manipulation, data cleaning
# why the pandas is from the numpy?
# because the pandas is built on top of the numpy, so the pandas can use the numpy functions and methods, and the pandas can also use the numpy data types, so the pandas is more powerful than the numpy, and the pandas is more flexible than the numpy, and the pandas is more efficient than the numpy, and the pandas is more user-friendly than the numpy, and the pandas is more versatile than the numpy, and the pandas is more popular than the numpy, and the pandas is more widely used than the numpy, and the pandas is more widely supported than the numpy, and the pandas is more widely adopted than the numpy, and the pandas is more widely accepted than the numpy, and the pandas is more widely recognized than the numpy, and the pandas is more widely appreciated than the numpy, and the pandas is more widely respected than the numpy, and the pandas is more widely admired than the numpy, and the pandas is more widely loved than the numpy, and the pandas is more widely cherished than the numpy, and the pandas is more widely valued than the numpy, and the pandas is more widely treasured than the numpy, and the pandas is more widely esteemed than the numpy, and the pandas is more widely honored than the numpy, and the pandas is more widely praised than the numpy, and the pandas is more widely celebrated than the numpy, and the pandas is more widely acclaimed than the numpy, and the pandas is more widely applauded than the numpy, and the pandas is more widely cheered than the numpy, and the pandas is more widely congratulated than the numpy, and the pandas is more widely commended than the numpy, and so on.
# pandas is more powerful than the numpy, and the pandas is more flexible than the numpy,
# and the pandas is more efficient than the numpy, and the pandas is more user-friendly than the numpy, and the pandas is more versatile than the numpy, and the pandas is more popular than the numpy, and the pandas is more widely used than the numpy, and the pandas is more widely supported than the numpy, and the pandas is more widely adopted than the numpy, and the pandas is more widely accepted than the numpy, and the pandas is more widely recognized than the numpy, and the pandas is more widely appreciated than the numpy, and the pandas is more widely respected than the numpy, and the pandas is more widely admired than the numpy, and the pandas is more widely loved than the numpy, and the pandas is more widely cherished than the numpy, and the pandas is more widely valued than the numpy, and the pandas is more widely treasured than the numpy, and the pandas is more widely esteemed than the numpy, and the pandas is more widely honored than the numpy, and the pandas is more widely praised than the numpy, and the pandas is more widely celebrated than the numpy, and the pandas is more widely acclaimed than the numpy, and so on.
# pandas is more powerful than the numpy, and the pandas is more flexible than the numpy,
# and the pandas is more efficient than the numpy, and the pandas is more user-friendly than the numpy, and the pandas is more versatile than the numpy, and the pandas is more popular than the numpy, and the pandas is more widely used than the numpy, and the pandas is more widely supported than the numpy, and the pandas is more widely adopted than the numpy, and the pandas is more widely accepted than the numpy, and the pandas is more widely recognized than the numpy, and the pandas is more widely appreciated than the numpy, and the pandas is more widely respected than the numpy, and the pandas is more widely admired than the numpy, and the pandas is more widely loved than the numpy, and the pandas is more widely cherished than the numpy, and the pandas is more widely valued than the numpy, and the pandas is more widely treasured than the numpy, and the pandas is more widely esteemed than the numpy, and so on.
# pandas is more powerful than the numpy, and the pandas is more flexible than the numpy,

In [42]:
s=pb.Series([1, 2, 3, 4, 5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# give me the normal thing to do in pandas
# normal operations in pandas include:
# 1. Creating Series and DataFrames
# 2. Reading and writing data from/to files (CSV, Excel, JSON, etc.)
# 3. Data selection and filtering
# 4. Data manipulation (adding columns, renaming columns, etc.)
# 5. Data aggregation (grouping, summing, averaging, etc.)
# 6. Handling missing data
# 7. Merging and joining datasets
# 8. Sorting data
# 9. Applying functions to data
# 10. Visualizing data using matplotlib or seaborn

In [ ]:
s=pb.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print(s)
print(s['a'])
print(s[0])

a    1
b    2
c    3
d    4
e    5
dtype: int64
1
1

C:\Users\V\AppData\Local\Temp\ipykernel_11376\3423236798.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [ ]:
# swries of dictionary
d={'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
s=pb.Series(d)# we can create a series from a dictionary, and the keys of the dictionary will be the index of the series, and the values of the dictionary will be the values of the series.
print(s)
print(d)

a    1
b    2
c    3
d    4
e    5
dtype: int64
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [ ]:
data={
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'age': [25, 30, 35, 40, 45],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}#    |---->this name is the column name, and this list is the values of the column, and the length of the list should be the same for all columns, and the number of columns should be the same for all rows, and the number of rows should be the same for all columns, and so on.
df=pb.DataFrame(data,index=['stu1', 'stu2', 'stu3', 'stu4', 'stu5'])# we can create a dataframe from a dictionary, and the keys of the dictionary will be the column names of the dataframe, and the values of the dictionary will be the values of the columns of the dataframe, and the index of the dataframe will be the index of the dictionary, and so on.   
print(df)
df.set_index('name', inplace=True)# we can set the index of the dataframe to a column, and the column will be removed from the dataframe, and the index will be set to the values of the column, and so on.
print(df)
df.set_flags(allows_duplicate_labels=False)# we can allow duplicate labels in the index of the dataframe, and the duplicate labels will be allowed in the index, and so on.
print(df)

         name  age          city
stu1    Alice   25      New York
stu2      Bob   30   Los Angeles
stu3  Charlie   35       Chicago
stu4    David   40       Houston
stu5      Eve   45       Phoenix
stu6    Frank   50  Philadelphia
stu7    Alice   25        Boston
         age          city
name
Alice     25      New York
Bob       30   Los Angeles
Charlie   35       Chicago
David     40       Houston
Eve       45       Phoenix
Frank     50  Philadelphia
Alice     25        Boston
         age          city
name
Alice     25      New York
Bob       30   Los Angeles
Charlie   35       Chicago
David     40       Houston
Eve       45       Phoenix
Frank     50  Philadelphia
Alice     25        Boston

In [ ]:
df1=pb.DataFrame({
    "Name":["Amanda", "Brian", "Charlie", "David", "Eve"],
    "Age":[28, 34, 29, 42, 31],
    "Marks":[85, 92, 78, 88, 90]
})
print(df1)
df1.head()

      Name  Age  Marks
0   Amanda   28     85
1    Brian   34     92
2  Charlie   29     78
3    David   42     88
4      Eve   31     90

      Name  Age  Marks
0   Amanda   28     85
1    Brian   34     92
2  Charlie   29     78
3    David   42     88
4      Eve   31     90

In [ ]:
df1.tail()    #tail() method is used to get the last n rows of the dataframe, where n is the number of rows to be returned. By default, it returns the last 5 rows of the dataframe.

      Name  Age  Marks
0   Amanda   28     85
1    Brian   34     92
2  Charlie   29     78
3    David   42     88
4      Eve   31     90

In [ ]:
df2=pb.DataFrame({
    "Name":["Frank", "Grace", "Hannah", "Ian", "Jack", "Karen", "Leo", "Mia", "Nina", "Oscar"],
    "Age":[27, 33, 30, 41, 29, 35, 28, 32, 37, 40],
    "Marks":[82, 89, 80, 87, 91, 79, 85, 90, 84, 86]
})
df2.head()
#df2.tail()
#df2.info()
df2.describe()

             Age      Marks
count  10.000000  10.000000
mean   33.200000  85.300000
std     4.939636   4.110961
min    27.000000  79.000000
25%    29.250000  82.500000
50%    32.500000  85.500000
75%    36.500000  88.500000
max    41.000000  91.000000

In [ ]:
df1["Age"]              # This line of code is used to access the column "Age" of the dataframe df1. It will return a series containing the values of the column "Age".
df1["Age"].mean()       # mean() method is used to get the mean of the values in the column "Age" of the dataframe df1.

np.float64(32.8)

In [ ]:
df1[df1['Age'] > 31]

    Name  Age  Marks
1  Brian   34     92
3  David   42     88

In [ ]:
df1[(df1['Marks'] > 80) & (df1['Age'] < 31)]

     Name  Age  Marks
0  Amanda   28     85

In [ ]:
df1.sort_values(by='Marks', ascending=False) # sort_values() method is used to sort the dataframe by the values of the column "Marks" in descending order. The parameter by is used to specify the column by which the dataframe should be sorted, and the parameter ascending is used to specify whether the sorting should be in ascending order (True) or descending order (False). In this case, we want to sort the dataframe in descending order, so we set ascending to False.

      Name  Age  Marks
1    Brian   34     92
4      Eve   31     90
3    David   42     88
0   Amanda   28     85
2  Charlie   29     78

In [ ]:
df1["Age"].value_counts()

Age
28    1
34    1
29    1
42    1
31    1
Name: count, dtype: int64

In [ ]:
df3=pb.DataFrame({
    "Name":["Alice", "Bob", "Charlie", "David", None],
    "Age":[25, 30, None, 40, 45],
    "Marks":[80, None, 90, 95, None]
})
print(df3)

      Name   Age  Marks
0    Alice  25.0   80.0
1      Bob  30.0    NaN
2  Charlie   NaN   90.0
3    David  40.0   95.0
4     None  45.0    NaN

In [ ]:
df3.isnull()    # isnull() method is used to check for missing values in the dataframe df3. It will return a dataframe of the same shape as df3, where each cell will contain True if the corresponding cell in df3 is null (missing) and False otherwise.

# df3.isnull().sum()   # sum() method is used to get the total number of missing values in each column of the dataframe df3. It will return a series where the index is the column names and the values are the total number of missing values in each column.

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4   True  False   True

In [ ]:
df3.isnull().sum()

Name     1
Age      1
Marks    2
dtype: int64

In [ ]:
df3.dropna()   # dropna() method is used to remove the rows that contain missing values from the dataframe df3. It will return a new dataframe that contains only the rows that do not have any missing values. By default, it will remove any row that has at least one missing value, but you can also specify how to handle missing values using the parameters of the dropna() method.

    Name   Age  Marks
0  Alice  25.0   80.0
3  David  40.0   95.0

pandas tasks

In [22]:
import pandas as pb

In [33]:
arr1=pb.DataFrame({
    "Name":["Aman","Saurav","Karan","Shubham","Abhishek","Missing","Sameer"],
    "Age":[22,23,None,22,25,24,26],
    "Marks":[85,None,88,90,56,72,None],
    "Subject":["Math","Physics","Math","Chemistry","Math","Physics","Chemistry"]
})
print(arr1.shape)
print(arr1.dtypes)
print(max(arr1["Age"].dropna()), max(arr1["Marks"].dropna()))
print(arr1.describe())

(7, 4)
Name        object
Age        float64
Marks      float64
Subject     object
dtype: object
26.0 90.0
             Age      Marks
count   6.000000   5.000000
mean   23.666667  78.200000
std     1.632993  14.254824
min    22.000000  56.000000
25%    22.250000  72.000000
50%    23.500000  85.000000
75%    24.750000  88.000000
max    26.000000  90.000000

In [5]:
print(arr1["Name"],arr1["Marks"])

0        Aman
1      Saurav
2       Karan
3     Shubham
4    Abhishek
5     Missing
6      Sameer
Name: Name, dtype: object 0    85.0
1     NaN
2    88.0
3    90.0
4    56.0
5    72.0
6     NaN
Name: Marks, dtype: float64

In [6]:
a=arr1[arr1["Marks"]>80]
print(a)
b=a[a["Age"]>22]
print(b)

      Name   Age  Marks    Subject
0     Aman  22.0   85.0       Math
2    Karan   NaN   88.0       Math
3  Shubham  22.0   90.0  Chemistry
Empty DataFrame
Columns: [Name, Age, Marks, Subject]
Index: []

In [7]:
arr1.sort_values(by="Marks", ascending=False)

       Name   Age  Marks    Subject
3   Shubham  22.0   90.0  Chemistry
2     Karan   NaN   88.0       Math
0      Aman  22.0   85.0       Math
5   Missing  24.0   72.0    Physics
4  Abhishek  25.0   56.0       Math
1    Saurav  23.0    NaN    Physics
6    Sameer  26.0    NaN  Chemistry

In [8]:
arr1.head(2)

     Name   Age  Marks  Subject
0    Aman  22.0   85.0     Math
1  Saurav  23.0    NaN  Physics

In [9]:
print(arr1.isnull().sum())
print(arr1["Marks"].isnull())

Name       0
Age        1
Marks      2
Subject    0
dtype: int64
0    False
1     True
2    False
3    False
4    False
5    False
6     True
Name: Marks, dtype: bool

In [14]:
import numpy as np

In [15]:
arr1["Marks"].nlargest(2) # nlargest give the n top values

3    90.0
2    88.0
Name: Marks, dtype: float64

In [40]:
arr1["Marks"].dtypes

dtype('float64')

In [36]:
data={
    "Name":["Aman","Saurav","Karan","Shubham","Abhishek","Missing","Sameer"],
    "Age":[22,23,None,22,25,24,26],
    "Marks":[85,None,88,90,56,72,None],
    "Subject":["Math","Physics","Math","Chemistry","Math","Physics","Chemistry"]
}
df=pb.DataFrame(data)
print(df)

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
1    Saurav  23.0    NaN    Physics
2     Karan   NaN   88.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5   Missing  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry

In [ ]:
df.groupby("Subject")["Marks"].mean()

Subject
Chemistry    90
Math         76
Physics      72
Name: Marks, dtype: int64

In [64]:
df.groupby("Subject")["Marks"].agg(["mean","max","min"])

                mean   max   min
Subject
Chemistry  90.000000  90.0  90.0
Math       76.333333  88.0  56.0
Physics    72.000000  72.0  72.0

In [68]:
df.groupby(["Subject","Age"])["Marks"].agg(["mean","max","min"])

                mean   max   min
Subject   Age
Chemistry 22.0  90.0  90.0  90.0
          26.0   NaN   NaN   NaN
Math      22.0  85.0  85.0  85.0
          25.0  56.0  56.0  56.0
Physics   23.0   NaN   NaN   NaN
          24.0  72.0  72.0  72.0

In [67]:
print(np.where(df.isnull().any(axis=1), "Missing", df["Name"]))
print(df[(df.isnull().any(axis=1)==False)]["Name"])

['Aman' 'Missing' 'Missing' 'Shubham' 'Abhishek' 'Missing' 'Missing']
0        Aman
3     Shubham
4    Abhishek
5     Missing
Name: Name, dtype: object

2

In [74]:
import pandas as Pd
dataset=Pd.DataFrame({
    "name":["Alice", "Bob", "Charlie", "David", "Eve","Frank", "Grace", "Hannah", "Ian", "Jack"],
    "department":["HR", "Finance", "IT", "Marketing", "HR",None, "IT", "Marketing", "HR", "Finance"],
    "salary":[50000, 60000, 55000, None, 52000, 58000, 62000, 57000, 54000, 61000],
    "role":[None, "Analyst", "Developer", "Executive", "Assistant","Manager", "Analyst", "Developer", "Executive", "Assistant"],
    "experience":[5, 3, 4, 6, 2, 7, 4, 5, None, 6],
    "score":[85, 90, 80, None, 88, 92, 87, 89, 84, 91],
})
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     object
 1   department  9 non-null      object
 2   salary      9 non-null      float64
 3   role        9 non-null      object
 4   experience  9 non-null      float64
 5   score       9 non-null      float64
dtypes: float64(3), object(3)
memory usage: 612.0+ bytes

In [77]:
print(dataset.groupby("department")["salary"].mean())
print("----------Performance score---------------")
print(dataset.groupby("department")["score"].mean())

department
Finance      60500.0
HR           52000.0
IT           58500.0
Marketing    57000.0
Name: salary, dtype: float64
----------Performance score---------------
department
Finance      90.500000
HR           85.666667
IT           83.500000
Marketing    89.000000
Name: score, dtype: float64

In [83]:
print(dataset.groupby("department")["score"].count())

department
Finance      2
HR           3
IT           2
Marketing    1
Name: score, dtype: int64

In [84]:
dataset.groupby("department")["salary"].agg(["mean","max","min"])

               mean      max      min
department
Finance     60500.0  61000.0  60000.0
HR          52000.0  54000.0  50000.0
IT          58500.0  62000.0  55000.0
Marketing   57000.0  57000.0  57000.0

In [86]:
dataset.groupby("department")["score"].agg(["mean","max","min"])

                 mean   max   min
department
Finance     90.500000  91.0  90.0
HR          85.666667  88.0  84.0
IT          83.500000  87.0  80.0
Marketing   89.000000  89.0  89.0

In [ ]:
#EDA