<!-- in pandas we use for  -->
<!-- in xl we con't work for the  -->
<!-- mixed types we can do  -->

In [1]:
import pandas as pb
# numpy vs pandas
# in numpy we can't use the different data to integer, float, string
# but in pandas we can use the different data to integer, float, string
# numpy us for image processing, machine learning, deep learning
# pandas is for data analysis, data manipulation, data cleaning
# why the pandas is from the numpy?
# because the pandas is built on top of the numpy, so the pandas can use the numpy functions and methods, and the pandas can also use the numpy data types, so the pandas is more powerful than the numpy, and the pandas is more flexible than the numpy, and the pandas is more efficient than the numpy, and the pandas is more user-friendly than the numpy, and the pandas is more versatile than the numpy, and the pandas is more popular than the numpy, and the pandas is more widely used than the numpy, and the pandas is more widely supported than the numpy, and the pandas is more widely adopted than the numpy, and the pandas is more widely accepted than the numpy, and the pandas is more widely recognized than the numpy, and the pandas is more widely appreciated than the numpy, and the pandas is more widely respected than the numpy, and the pandas is more widely admired than the numpy, and the pandas is more widely loved than the numpy, and the pandas is more widely cherished than the numpy, and the pandas is more widely valued than the numpy, and the pandas is more widely treasured than the numpy, and the pandas is more widely esteemed than the numpy, and the pandas is more widely honored than the numpy, and the pandas is more widely praised than the numpy, and the pandas is more widely celebrated than the numpy, and the pandas is more widely acclaimed than the numpy, and the pandas is more widely applauded than the numpy, and the pandas is more widely cheered than the numpy, and the pandas is more widely congratulated than the numpy, and the pandas is more widely commended than the numpy, and so on.
# pandas is more powerful than the numpy, and the pandas is more flexible than the numpy,
# and the pandas is more efficient than the numpy, and the pandas is more user-friendly than the numpy, and the pandas is more versatile than the numpy, and the pandas is more popular than the numpy, and the pandas is more widely used than the numpy, and the pandas is more widely supported than the numpy, and the pandas is more widely adopted than the numpy, and the pandas is more widely accepted than the numpy, and the pandas is more widely recognized than the numpy, and the pandas is more widely appreciated than the numpy, and the pandas is more widely respected than the numpy, and the pandas is more widely admired than the numpy, and the pandas is more widely loved than the numpy, and the pandas is more widely cherished than the numpy, and the pandas is more widely valued than the numpy, and the pandas is more widely treasured than the numpy, and the pandas is more widely esteemed than the numpy, and the pandas is more widely honored than the numpy, and the pandas is more widely praised than the numpy, and the pandas is more widely celebrated than the numpy, and the pandas is more widely acclaimed than the numpy, and so on.
# pandas is more powerful than the numpy, and the pandas is more flexible than the numpy,
# and the pandas is more efficient than the numpy, and the pandas is more user-friendly than the numpy, and the pandas is more versatile than the numpy, and the pandas is more popular than the numpy, and the pandas is more widely used than the numpy, and the pandas is more widely supported than the numpy, and the pandas is more widely adopted than the numpy, and the pandas is more widely accepted than the numpy, and the pandas is more widely recognized than the numpy, and the pandas is more widely appreciated than the numpy, and the pandas is more widely respected than the numpy, and the pandas is more widely admired than the numpy, and the pandas is more widely loved than the numpy, and the pandas is more widely cherished than the numpy, and the pandas is more widely valued than the numpy, and the pandas is more widely treasured than the numpy, and the pandas is more widely esteemed than the numpy, and so on.
# pandas is more powerful than the numpy, and the pandas is more flexible than the numpy,

In [2]:
s=pb.Series([1, 2, 3, 4, 5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# give me the normal thing to do in pandas
# normal operations in pandas include:
# 1. Creating Series and DataFrames
# 2. Reading and writing data from/to files (CSV, Excel, JSON, etc.)
# 3. Data selection and filtering
# 4. Data manipulation (adding columns, renaming columns, etc.)
# 5. Data aggregation (grouping, summing, averaging, etc.)
# 6. Handling missing data
# 7. Merging and joining datasets
# 8. Sorting data
# 9. Applying functions to data
# 10. Visualizing data using matplotlib or seaborn

In [5]:
s=pb.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print(s)
print(s['a'])
print(s[0])

a    1
b    2
c    3
d    4
e    5
dtype: int64
1
1

C:\Users\V\AppData\Local\Temp\ipykernel_11376\3423236798.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [ ]:
# swries of dictionary
d={'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
s=pb.Series(d)# we can create a series from a dictionary, and the keys of the dictionary will be the index of the series, and the values of the dictionary will be the values of the series.
print(s)
print(d)

a    1
b    2
c    3
d    4
e    5
dtype: int64
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [ ]:
data={
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'age': [25, 30, 35, 40, 45],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}#    |---->this name is the column name, and this list is the values of the column, and the length of the list should be the same for all columns, and the number of columns should be the same for all rows, and the number of rows should be the same for all columns, and so on.
df=pb.DataFrame(data,index=['stu1', 'stu2', 'stu3', 'stu4', 'stu5'])# we can create a dataframe from a dictionary, and the keys of the dictionary will be the column names of the dataframe, and the values of the dictionary will be the values of the columns of the dataframe, and the index of the dataframe will be the index of the dictionary, and so on.   
print(df)
df.set_index('name', inplace=True)# we can set the index of the dataframe to a column, and the column will be removed from the dataframe, and the index will be set to the values of the column, and so on.
print(df)
df.set_flags(allows_duplicate_labels=False)# we can allow duplicate labels in the index of the dataframe, and the duplicate labels will be allowed in the index, and so on.
print(df)

         name  age          city
stu1    Alice   25      New York
stu2      Bob   30   Los Angeles
stu3  Charlie   35       Chicago
stu4    David   40       Houston
stu5      Eve   45       Phoenix
stu6    Frank   50  Philadelphia
stu7    Alice   25        Boston
         age          city
name
Alice     25      New York
Bob       30   Los Angeles
Charlie   35       Chicago
David     40       Houston
Eve       45       Phoenix
Frank     50  Philadelphia
Alice     25        Boston
         age          city
name
Alice     25      New York
Bob       30   Los Angeles
Charlie   35       Chicago
David     40       Houston
Eve       45       Phoenix
Frank     50  Philadelphia
Alice     25        Boston

In [ ]:
df1=pb.DataFrame({
    "Name":["Amanda", "Brian", "Charlie", "David", "Eve"],
    "Age":[28, 34, 29, 42, 31],
    "Marks":[85, 92, 78, 88, 90]
})
print(df1)
df1.head()

      Name  Age  Marks
0   Amanda   28     85
1    Brian   34     92
2  Charlie   29     78
3    David   42     88
4      Eve   31     90

      Name  Age  Marks
0   Amanda   28     85
1    Brian   34     92
2  Charlie   29     78
3    David   42     88
4      Eve   31     90

In [34]:
df1.tail()    #tail() method is used to get the last n rows of the dataframe, where n is the number of rows to be returned. By default, it returns the last 5 rows of the dataframe.

      Name  Age  Marks
0   Amanda   28     85
1    Brian   34     92
2  Charlie   29     78
3    David   42     88
4      Eve   31     90

In [43]:
df2=pb.DataFrame({
    "Name":["Frank", "Grace", "Hannah", "Ian", "Jack", "Karen", "Leo", "Mia", "Nina", "Oscar"],
    "Age":[27, 33, 30, 41, 29, 35, 28, 32, 37, 40],
    "Marks":[82, 89, 80, 87, 91, 79, 85, 90, 84, 86]
})
df2.head()
#df2.tail()
#df2.info()
df2.describe()

             Age      Marks
count  10.000000  10.000000
mean   33.200000  85.300000
std     4.939636   4.110961
min    27.000000  79.000000
25%    29.250000  82.500000
50%    32.500000  85.500000
75%    36.500000  88.500000
max    41.000000  91.000000

In [ ]:
df1["Age"]              # This line of code is used to access the column "Age" of the dataframe df1. It will return a series containing the values of the column "Age".
df1["Age"].mean()       # mean() method is used to get the mean of the values in the column "Age" of the dataframe df1.

np.float64(32.8)

In [ ]:
df1[df1['Age'] > 31]

    Name  Age  Marks
1  Brian   34     92
3  David   42     88

In [52]:
df1[(df1['Marks'] > 80) & (df1['Age'] < 31)]

     Name  Age  Marks
0  Amanda   28     85

In [ ]:
df1.sort_values(by='Marks', ascending=False) # sort_values() method is used to sort the dataframe by the values of the column "Marks" in descending order. The parameter by is used to specify the column by which the dataframe should be sorted, and the parameter ascending is used to specify whether the sorting should be in ascending order (True) or descending order (False). In this case, we want to sort the dataframe in descending order, so we set ascending to False.

      Name  Age  Marks
1    Brian   34     92
4      Eve   31     90
3    David   42     88
0   Amanda   28     85
2  Charlie   29     78

In [54]:
df1["Age"].value_counts()

Age
28    1
34    1
29    1
42    1
31    1
Name: count, dtype: int64